<?php

declare(strict_types=1);

namespace Kinescope\DTO\Video;

use Kinescope\DTO\Common\MetaDTO;
use Kinescope\DTO\Common\PaginatedResponse;
use Kinescope\Enum\SubtitleLanguage;

/**
 * Paginated list of subtitles.
 *
 * @extends PaginatedResponse<SubtitleDTO>
 */
final readonly class SubtitleListResult extends PaginatedResponse
{
    /**
     * Create a SubtitleListResult from API response array.
     *
     * @param array<string, mixed> $response Raw API response
     *
     * @return self
     */
    public static function fromArray(array $response): self
    {
        $data = [];

        if (isset($response['data']) && is_array($response['data'])) {
            $data = array_map(
                static fn (array $item): SubtitleDTO => SubtitleDTO::fromArray($item),
                $response['data']
            );
        }

        $meta = MetaDTO::fromArray($response['meta'] ?? []);

        return new self($data, $meta);
    }

    /**
     * Get default subtitle.
     *
     * @return SubtitleDTO|null
     */
    public function getDefault(): ?SubtitleDTO
    {
        return $this->find(
            static fn (SubtitleDTO $subtitle): bool => $subtitle->isDefault
        );
    }

    /**
     * Get subtitle by language.
     *
     * @param SubtitleLanguage $language Language to find
     *
     * @return SubtitleDTO|null
     */
    public function getByLanguage(SubtitleLanguage $language): ?SubtitleDTO
    {
        return $this->find(
            static fn (SubtitleDTO $subtitle): bool => $subtitle->language === $language
        );
    }

    /**
     * Get subtitle by language code string.
     *
     * @param string $languageCode Language code (e.g., "en", "ru")
     *
     * @return SubtitleDTO|null
     */
    public function getByLanguageCode(string $languageCode): ?SubtitleDTO
    {
        return $this->find(
            static fn (SubtitleDTO $subtitle): bool =>
                $subtitle->getLanguageCode() === $languageCode
        );
    }

    /**
     * Get all auto-generated subtitles.
     *
     * @return array<SubtitleDTO>
     */
    public function getAutoGenerated(): array
    {
        return $this->filter(
            static fn (SubtitleDTO $subtitle): bool => $subtitle->isAutoGenerated
        );
    }

    /**
     * Get all manually uploaded subtitles.
     *
     * @return array<SubtitleDTO>
     */
    public function getManual(): array
    {
        return $this->filter(
            static fn (SubtitleDTO $subtitle): bool => ! $subtitle->isAutoGenerated
        );
    }

    /**
     * Get all available language codes.
     *
     * @return array<string>
     */
    public function getAvailableLanguages(): array
    {
        $languages = [];

        foreach ($this->data as $subtitle) {
            $code = $subtitle->getLanguageCode();

            if ($code !== null && ! in_array($code, $languages, true)) {
                $languages[] = $code;
            }
        }

        return $languages;
    }

    /**
     * Check if subtitles for a specific language exist.
     *
     * @param SubtitleLanguage $language Language to check
     *
     * @return bool
     */
    public function hasLanguage(SubtitleLanguage $language): bool
    {
        return $this->getByLanguage($language) !== null;
    }

    /**
     * Find subtitle by ID.
     *
     * @param string $id Subtitle identifier
     *
     * @return SubtitleDTO|null
     */
    public function findById(string $id): ?SubtitleDTO
    {
        return $this->find(
            static fn (SubtitleDTO $subtitle): bool => $subtitle->id === $id
        );
    }
}
