<?php

declare(strict_types=1);

namespace Kinescope\DTO\Video;

use DateTimeImmutable;
use DateTimeInterface;
use Kinescope\Enum\SubtitleLanguage;

/**
 * Video subtitle data transfer object.
 *
 * Represents a subtitle track for a video.
 */
final readonly class SubtitleDTO
{
    /**
     * Create a new SubtitleDTO instance.
     *
     * @param string $id Subtitle unique identifier
     * @param string $videoId Parent video identifier
     * @param string $title Subtitle title/label
     * @param SubtitleLanguage|null $language Language code
     * @param string|null $languageRaw Raw language code from API (if not in enum)
     * @param string|null $url URL to download the subtitle file
     * @param string|null $format Subtitle format (srt, vtt, etc.)
     * @param bool $isDefault Whether this is default subtitle
     * @param bool $isAutoGenerated Whether this was auto-generated
     * @param DateTimeImmutable|null $createdAt Creation timestamp
     * @param DateTimeImmutable|null $updatedAt Last update timestamp
     */
    public function __construct(
        public string $id,
        public string $videoId,
        public string $title,
        public ?SubtitleLanguage $language,
        public ?string $languageRaw,
        public ?string $url,
        public ?string $format,
        public bool $isDefault,
        public bool $isAutoGenerated,
        public ?DateTimeImmutable $createdAt,
        public ?DateTimeImmutable $updatedAt,
    ) {
    }

    /**
     * Create a SubtitleDTO from API response array.
     *
     * @param array<string, mixed> $data Raw API response data
     *
     * @return self
     */
    public static function fromArray(array $data): self
    {
        $languageRaw = isset($data['language']) ? (string) $data['language'] : null;
        $language = $languageRaw !== null
            ? SubtitleLanguage::tryFrom($languageRaw)
            : null;

        return new self(
            id: (string) $data['id'],
            videoId: (string) ($data['video_id'] ?? ''),
            title: (string) ($data['title'] ?? ''),
            language: $language,
            languageRaw: $languageRaw,
            url: isset($data['url']) ? (string) $data['url'] : null,
            format: isset($data['format']) ? (string) $data['format'] : null,
            isDefault: (bool) ($data['is_default'] ?? false),
            isAutoGenerated: (bool) ($data['is_auto_generated'] ?? false),
            createdAt: isset($data['created_at'])
                ? new DateTimeImmutable($data['created_at'])
                : null,
            updatedAt: isset($data['updated_at'])
                ? new DateTimeImmutable($data['updated_at'])
                : null,
        );
    }

    /**
     * Get the language name in English.
     *
     * @return string|null
     */
    public function getLanguageName(): ?string
    {
        return $this->language?->getEnglishName();
    }

    /**
     * Get the native language name.
     *
     * @return string|null
     */
    public function getNativeLanguageName(): ?string
    {
        return $this->language?->getNativeName();
    }

    /**
     * Check if the language is right-to-left.
     *
     * @return bool
     */
    public function isRtl(): bool
    {
        return $this->language?->isRtl() ?? false;
    }

    /**
     * Check if this is a known language (in the enum).
     *
     * @return bool
     */
    public function hasKnownLanguage(): bool
    {
        return $this->language !== null;
    }

    /**
     * Get the effective language code.
     *
     * @return string|null
     */
    public function getLanguageCode(): ?string
    {
        return $this->language !== null ? $this->language->value : $this->languageRaw;
    }

    /**
     * Check if subtitle has a download URL.
     *
     * @return bool
     */
    public function hasUrl(): bool
    {
        return $this->url !== null && $this->url !== '';
    }

    /**
     * Convert to array representation.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'video_id' => $this->videoId,
            'title' => $this->title,
            'language' => $this->getLanguageCode(),
            'url' => $this->url,
            'format' => $this->format,
            'is_default' => $this->isDefault,
            'is_auto_generated' => $this->isAutoGenerated,
            'created_at' => $this->createdAt?->format(DateTimeInterface::ATOM),
            'updated_at' => $this->updatedAt?->format(DateTimeInterface::ATOM),
        ];
    }
}
