<?php

declare(strict_types=1);

namespace Kinescope\Tests\Unit\DTO\Subtitle;

use Kinescope\DTO\Video\SubtitleDTO;
use Kinescope\Enum\SubtitleLanguage;
use PHPUnit\Framework\TestCase;

class SubtitleDTOTest extends TestCase
{
    public function testFromArrayCreatesValidSubtitleDTO(): void
    {
        $data = [
            'id' => '550e8400-e29b-41d4-a716-446655440000',
            'video_id' => 'video-uuid',
            'title' => 'English',
            'language' => 'en',
            'url' => 'https://example.com/subtitle.vtt',
            'is_default' => true,
            'is_auto_generated' => false,
            'created_at' => '2024-01-01T00:00:00Z',
            'updated_at' => '2024-01-02T00:00:00Z',
        ];

        $subtitle = SubtitleDTO::fromArray($data);

        $this->assertEquals('550e8400-e29b-41d4-a716-446655440000', $subtitle->id);
        $this->assertEquals('video-uuid', $subtitle->videoId);
        $this->assertEquals('English', $subtitle->title);
        $this->assertEquals(SubtitleLanguage::EN, $subtitle->language);
        $this->assertEquals('en', $subtitle->languageRaw);
        $this->assertTrue($subtitle->isDefault);
        $this->assertFalse($subtitle->isAutoGenerated);
        $this->assertEquals('https://example.com/subtitle.vtt', $subtitle->url);
    }

    public function testFromArrayWithMinimalData(): void
    {
        $data = [
            'id' => '550e8400-e29b-41d4-a716-446655440000',
            'video_id' => 'video-uuid',
            'title' => 'English',
            'language' => 'en',
        ];

        $subtitle = SubtitleDTO::fromArray($data);

        $this->assertEquals('550e8400-e29b-41d4-a716-446655440000', $subtitle->id);
        $this->assertEquals('video-uuid', $subtitle->videoId);
        $this->assertEquals('English', $subtitle->title);
        $this->assertEquals(SubtitleLanguage::EN, $subtitle->language);
        $this->assertFalse($subtitle->isDefault);
        $this->assertFalse($subtitle->isAutoGenerated);
        $this->assertNull($subtitle->url);
    }

    public function testToArrayReturnsCorrectStructure(): void
    {
        $data = [
            'id' => '550e8400-e29b-41d4-a716-446655440000',
            'video_id' => 'video-uuid',
            'title' => 'English',
            'language' => 'en',
            'url' => 'https://example.com/subtitle.vtt',
            'is_default' => true,
            'is_auto_generated' => false,
            'created_at' => '2024-01-01T00:00:00Z',
            'updated_at' => '2024-01-01T00:00:00Z',
        ];

        $subtitle = SubtitleDTO::fromArray($data);
        $array = $subtitle->toArray();

        $this->assertEquals('550e8400-e29b-41d4-a716-446655440000', $array['id']);
        $this->assertEquals('video-uuid', $array['video_id']);
        $this->assertEquals('English', $array['title']);
        $this->assertEquals('en', $array['language']);
        $this->assertTrue($array['is_default']);
        $this->assertFalse($array['is_auto_generated']);
    }

    public function testGetLanguageNameReturnsEnglishName(): void
    {
        $subtitle = SubtitleDTO::fromArray([
            'id' => '1',
            'video_id' => 'v1',
            'title' => 'English',
            'language' => 'en',
        ]);

        $this->assertEquals('English', $subtitle->getLanguageName());
    }

    public function testGetNativeLanguageNameReturnsNativeName(): void
    {
        $subtitle = SubtitleDTO::fromArray([
            'id' => '1',
            'video_id' => 'v1',
            'title' => 'Русский',
            'language' => 'ru',
        ]);

        $this->assertEquals('Русский', $subtitle->getNativeLanguageName());
    }

    public function testIsRtlReturnsTrueForArabic(): void
    {
        $subtitle = SubtitleDTO::fromArray([
            'id' => '1',
            'video_id' => 'v1',
            'title' => 'Arabic',
            'language' => 'ar',
        ]);

        $this->assertTrue($subtitle->isRtl());
    }

    public function testIsRtlReturnsFalseForLatin(): void
    {
        $subtitle = SubtitleDTO::fromArray([
            'id' => '1',
            'video_id' => 'v1',
            'title' => 'English',
            'language' => 'en',
        ]);

        $this->assertFalse($subtitle->isRtl());
    }

    public function testHasKnownLanguageReturnsTrueForEnumLanguage(): void
    {
        $subtitle = SubtitleDTO::fromArray([
            'id' => '1',
            'video_id' => 'v1',
            'title' => 'English',
            'language' => 'en',
        ]);

        $this->assertTrue($subtitle->hasKnownLanguage());
    }

    public function testHasKnownLanguageReturnsFalseForUnknownLanguage(): void
    {
        $subtitle = SubtitleDTO::fromArray([
            'id' => '1',
            'video_id' => 'v1',
            'title' => 'Custom',
            'language' => 'xx',
        ]);

        $this->assertFalse($subtitle->hasKnownLanguage());
    }

    public function testGetLanguageCodeReturnsEnumValueWhenKnown(): void
    {
        $subtitle = SubtitleDTO::fromArray([
            'id' => '1',
            'video_id' => 'v1',
            'title' => 'English',
            'language' => 'en',
        ]);

        $this->assertEquals('en', $subtitle->getLanguageCode());
    }

    public function testGetLanguageCodeReturnsRawWhenUnknown(): void
    {
        $subtitle = SubtitleDTO::fromArray([
            'id' => '1',
            'video_id' => 'v1',
            'title' => 'Custom',
            'language' => 'xx',
        ]);

        $this->assertEquals('xx', $subtitle->getLanguageCode());
    }

    public function testHasUrlReturnsTrueWhenUrlSet(): void
    {
        $subtitle = SubtitleDTO::fromArray([
            'id' => '1',
            'video_id' => 'v1',
            'title' => 'English',
            'language' => 'en',
            'url' => 'https://example.com/subtitle.vtt',
        ]);

        $this->assertTrue($subtitle->hasUrl());
    }

    public function testHasUrlReturnsFalseWhenNull(): void
    {
        $subtitle = SubtitleDTO::fromArray([
            'id' => '1',
            'video_id' => 'v1',
            'title' => 'English',
            'language' => 'en',
        ]);

        $this->assertFalse($subtitle->hasUrl());
    }
}
